linky.py: do not used unset 'erreurText'
'erreurText' key is used but is never set.

I then get the error:
    raise LinkyServiceException(html.unescape(res['etat']['erreurText']))
KeyError: 'erreurText'